---
title: |
  |  Angewandte Zuchtwertschätzung und 
  |  Angewandte statistische Methoden
author: "Birgit Gredler und Peter von Rohr"
date: "2016-02-04"
output: 
  html_document:
    toc_float: true
    toc: true
    theme: united
    highlight: tango
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

__Willkommen__ auf der Webseite von

- [751-6212-00L Angewandte Zuchtwertschätzung für Nutztiere](https://www.lehrbetrieb.ethz.ch/edoz/kommLerneinheitPre.do?i=0)
- [751-7602-00L	Angewandte statistische Methoden in den Nutztierwissenschaften](https://www.lehrbetrieb.ethz.ch/edoz/kommLehrveranstaltungPre.do?i=1&j=0)

## Beschreibung
Die Kursbeschreibung ist dem Vorlesungsverzeichnis entnommen.

### Angewandte Zuchtwertschätzung für Nutztiere
Die nationalen Zuchtwertschätzungen bei Rind, Schwein, Schaf und Ziege in der Schweiz werden anhand der verwendeten Methoden und Merkmalen erklärt. Zur Vertiefung werden fallweise Beispiele berechnet.

### Angewandte statistische Methoden in den Nutztierwissenschaften
Die genomische Selektion ist in der Tierzucht die Methode der Wahl, das Leistungspotential der Selektionskandidaten zu verbessern. In dieser Vorlesung wird erklärt, weshalb Regressionen in der genomischen Selektion nicht verwendet werden können und was dann die Alternativen sind. Die vorgestellten Konzepte werden mit Übungen in R veranschaulicht.

## Information
- Dozierende: Birgit Gredler (BG) und Peter von Rohr (PvR)
- Datum: Montag 8-10
- Ort: [LFW C11](http://www.mapsearch.ethz.ch/map/map.do?gebaeudeMap=LFW&lang=en)
- Exkursion: 7. März 2016 Besuch bei Qualitas AG und Braunvieh Schweiz in Zug

## Fragen
Fragen können jederzeit während der Vorlesung und während der Übungsstunde oder via Email gestellt werden: 

- BG (birgit.gredler `at` qualitasag.ch)
- PvR (peter.vonrohr `at` gmail.com)

## Material
Die Folien zur Vorlesung, die Übungen und die Lösungen zu den Übungen können von dieser Webseite heruntergeladen werden. 


### Folien

| Woche|Datum |Thema                |Wer    |
|-----:|:-----|:--------------------|:------|
|     1|22.02 |                     |BG     |
|     2|29.02 | [Angewandte Zuchtwertschätzung für Nutztiere](http://charlotte-ngs.github.io/GELASM/w2/Slides_20160222_Upload.pdf)                    |BG     |
|     3|07.03 |[L. Casanova: Braunvieh Schweiz](http://charlotte-ngs.github.io/GELASM/w3/Vortrag_BraunviehSchweizETHZ_StudentenMärz2016.pdf)                     |BG     |
|     3|07.03 |[J. Moll: Qualitas AG](http://charlotte-ngs.github.io/GELASM/w3/ETHZ_20160307.pptx.pdf)                     |BG     |
|     4|14.03 |[Zuchtwertschätzung Rind](http://charlotte-ngs.github.io/GELASM/w4/Slides_20160314.pptx.pdf)                     |BG     |
|     5|21.03 |[A. Hofer Zuchtwertschätzung Schwein](http://charlotte-ngs.github.io/GELASM/w5/ZuchtwertschätzungVorlesungETHZürich.pdf)                     |BG     |
|     5|21.03 |[Zuchtwertschätzung Rind](http://charlotte-ngs.github.io/GELASM/w5/Slides_20160321.pdf)                     |BG     |
|     6|28.03 |Ostermontag (frei)   |       |
|     7|04.04 |[Zuchtwertschätzung Rind/Schaf+Ziege](http://charlotte-ngs.github.io/GELASM/w7/Slides_20160404.pdf)                     |BG     |
|     8|11.04 | [Statistische Methoden](http://charlotte-ngs.github.io/GELASM/w8/asmas_w8_v1.pdf)  |PvR    |
|     9|18.04 | [Lineare Regression](http://charlotte-ngs.github.io/GELASM/w9/asmas_w9_v2.pdf)  |PvR    |
|    10|25.04 | [Lineare Regression (Teil 2)](http://charlotte-ngs.github.io/GELASM/w10/asmas_w10_v3.pdf) |PvR    |
|    11|02.05 | [Lineare Regression (Teil 3)](http://charlotte-ngs.github.io/GELASM/w11/asmas_w11_v4.pdf) |PvR    |
|    12|09.05 | [LASSO](http://charlotte-ngs.github.io/GELASM/w12/asmas_w12_v5.pdf) |PvR    |
|    13|16.05 |Pfingstmontag (frei) |       |
|    14|23.05 |                     |PvR    |
|    15|30.05 |Prüfung             |BG/PvR |


### Übungen

| Woche|Datum |Thema                |Wer    |
|-----:|:-----|:--------------------|:------|
|     1|22.02 |                     |BG     |
|     2|29.02 |                     |BG     |
|     3|07.03 |                     |BG     |
|     4|14.03 |                     |BG     |
|     5|21.03 |                     |BG     |
|     6|28.03 |Ostermontag (frei)   |       |
|     7|04.04 |                     |BG     |
|     8|11.04 |                     |PvR    |
|     9|18.04 | [Statistische Methoden](http://charlotte-ngs.github.io/GELASM/w9/asmas_w9_u1.pdf) |PvR    |
|    10|25.04 | [Lineare Regression](http://charlotte-ngs.github.io/GELASM/w10/asmas_w10_u2.pdf)  |PvR    |
|    11|02.05 | [Lineare Regression (Teil 2)](http://charlotte-ngs.github.io/GELASM/w11/asmas_w11_u3.pdf) |PvR    |
|    12|09.05 | [Lineare Regression (Teil 3)](http://charlotte-ngs.github.io/GELASM/w12/asmas_w12_u4.pdf) |PvR    |
|    13|16.05 |Pfingstmontag (frei) |       |
|    14|23.05 |                     |PvR    |
|    15|30.05 |Prüfung             |BG/PvR |


### Lösungen

|   | Woche|Datum |Thema                |Wer    |
|:--|-----:|:-----|:--------------------|:------|
|2  |     2|29.02 |                     |BG     |
|3  |     3|07.03 |                     |BG     |
|4  |     4|14.03 |                     |BG     |
|5  |     5|21.03 |                     |BG     |
|6  |     6|28.03 |Ostermontag (frei)   |       |
|7  |     7|04.04 |                     |BG     |
|8  |     8|11.04 |                     |PvR    |
|9  |     9|18.04 |                     |PvR    |
|10 |    10|25.04 | [Statistische Methoden](http://charlotte-ngs.github.io/GELASM/w9/asmas_w9_l1.pdf) |PvR    |
|11 |    11|02.05 | [Lineare Regression](http://charlotte-ngs.github.io/GELASM/w10/asmas_w10_l2.pdf) |PvR    |
|12 |    12|09.05 | [Lineare Regression (Teil 2)](http://charlotte-ngs.github.io/GELASM/w11/asmas_w11_l3.pdf)  |PvR    |
|13 |    13|16.05 |Pfingstmontag (frei) |       |
|14 |    14|23.05 |                     |PvR    |
|15 |    15|30.05 |Prüfung             |BG/PvR |


### Weiteres Material

|   | Woche|Datum |Thema                |Wer    |
|:--|-----:|:-----|:--------------------|:------|
|8  |     8|11.04 |[Präsentation Genomische Selektion](http://www.holstein.ch/medias/pdf/actualite/ad_2016_conf__rence_jacques_chesnais_-_d.ppt)  [(pdf)](http://charlotte-ngs.github.io/GELASM/w8/ad_2016_conf__rence_jacques_chesnais_-_d.pdf) |PvR    |
|9  |     9|18.04 |[Deregression](http://charlotte-ngs.github.io/GELASM/w9/DeRegressEbvSummaryGTF2009.pdf) |PvR    |
|10 |    10|25.04 |[Datensatz](http://charlotte-ngs.github.io/GELASM/w10/geno_sel_step1.csv) |PvR    |
|11 |    11|02.05 |[Asphalt-Datensatz](http://charlotte-ngs.github.io/GELASM/w11/asphalt.dat) |PvR    |

      
## Letzte Änderung
_`r paste(Sys.time(),paste0("(", Sys.info()[["user"]],")" ))`_
